include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - web/**
    - ios/**
    - .specify/**
    - .hermes/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    always_declare_return_types: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    eol_at_end_of_file: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_breaks: true
    unnecessary_underscores: false
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_enums: true
    use_named_constants: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
